### ISSUE TITLE
incompatible-pointer-types error near ch34x_device.set_termios

### ISSUE THREAD

**Issue by 6r1d** [juliagoda/CH341SER#34]
* System: Artix Linux (Arch Linux flavor)
* `uname -a` output: `Linux tardigrade 6.1.8-artix1-1 #1 SMP PREEMPT_DYNAMIC Sun, 29 Jan 2023 17:17:21 +0000 x86_64 GNU/Linux`
* Wrapper package: https://aur.archlinux.org/packages/ch34x-dkms-git

Build log:

```
DKMS make.log for ch34x-r62.e70c14c for kernel 6.1.8-artix1-1 (x86_64)
Сб 04 фев 2023 16:49:11 IST
make: Entering directory '/usr/lib/modules/6.1.8-artix1-1/build'
  CC [M]  /var/lib/dkms/ch34x/r62.e70c14c/build/ch34x.o
/var/lib/dkms/ch34x/r62.e70c14c/build/ch34x.c:1294:27: error: initialization of ‘void (*)(struct tty_struct *, struct usb_serial_port *, const struct ktermios *)’ from incompatible pointer type ‘void (*)(struct tty_struct *, struct usb_serial_port *, struct ktermios *)’ [-Werror=incompatible-pointer-types]
 1294 |         .set_termios    = ch34x_set_termios,
      |                           ^~~~~~~~~~~~~~~~~
/var/lib/dkms/ch34x/r62.e70c14c/build/ch34x.c:1294:27: note: (near initialization for ‘ch34x_device.set_termios’)
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:250: /var/lib/dkms/ch34x/r62.e70c14c/build/ch34x.o] Error 1
make: *** [Makefile:1992: /var/lib/dkms/ch34x/r62.e70c14c/build] Error 2
make: Leaving directory '/usr/lib/modules/6.1.8-artix1-1/build'
```

[Yay](https://github.com/Jguer/yay) (installer) log:

```
Building module:
Cleaning build area...
make -j6 KERNELRELEASE=6.1.8-artix1-1 -C /usr/lib/modules/6.1.8-artix1-1/build M=/var/lib/dkms/ch34x/r62.e70c14c/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.8-artix1-1 (x86_64)
Consult /var/lib/dkms/ch34x/r62.e70c14c/build/make.log for more information.
error: command failed to execute correctly
:: Running post-transaction hooks...
(1/1) Install DKMS modules
==> dkms install --no-depmod ch34x/r62.e70c14c -k 6.1.8-artix1-1
Error! Bad return status for module build on kernel: 6.1.8-artix1-1 (x86_64)
Consult /var/lib/dkms/ch34x/r62.e70c14c/build/make.log for more information.
==> WARNING: `dkms install --no-depmod ch34x/r62.e70c14c -k 6.1.8-artix1-1' exited 10
```
