### ISSUE TITLE
Failed to Compile on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by brian00715** [juliagoda/CH341SER#14]
```sh
~/Downloads/CH341SER-master$ sudo make
make -C /lib/modules/4.15.0-142-generic/build  M=/home/simon/Downloads/CH341SER-master 
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-142-generic'
  CC [M]  /home/simon/Downloads/CH341SER-master/ch34x.o
/home/simon/Downloads/CH341SER-master/ch34x.c:1292:20: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .write_room     = ch34x_write_room,
                    ^
/home/simon/Downloads/CH341SER-master/ch34x.c:1292:20: note: (near initialization for ‘ch34x_device.write_room’)
/home/simon/Downloads/CH341SER-master/ch34x.c:1293:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .chars_in_buffer = ch34x_chars_in_buffer,
                     ^
/home/simon/Downloads/CH341SER-master/ch34x.c:1293:21: note: (near initialization for ‘ch34x_device.chars_in_buffer’)
cc1: some warnings being treated as errors
scripts/Makefile.build:337: recipe for target '/home/simon/Downloads/CH341SER-master/ch34x.o' failed
make[2]: *** [/home/simon/Downloads/CH341SER-master/ch34x.o] Error 1
Makefile:1584: recipe for target '_module_/home/simon/Downloads/CH341SER-master' failed
make[1]: *** [_module_/home/simon/Downloads/CH341SER-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-142-generic'
Makefile:7: recipe for target 'default' failed
make: *** [default] Error 2
simon@ubuntu:~/Downloads/CH341SER-master$
```

**Comment by jimmyd-be** [comment]
Same issue in Ubuntu 20.04 LTS on raspberry pi arm64.

**Comment by sirlucjan** [comment]
Question for Ubuntu/Mint users. As a change made by the maintainer of this repository makes it impossible to build this on Arch Linux and therefore we would like to determine the culprit. I have two leads and would like to eliminate one of them. 

Could you see if this solution works for you? This time just clone my fork: https://github.com/sirlucjan/CH341SER

If it doesn't build up in you after this change, we can probably pinpoint the real cause of the problem.

**Comment by juliagoda** [comment]
I have tested for both cases - when there is a newer kernel with gcc and an older one, and it looks like the condition from the pull request adjusts correctly. Nevertheless, it would be good if others would confirm this. Users no longer need to clone the repo from @sirlucjan  if they don't want to, because the changes were accepted in the pull request
